zsh: add integration support

diff --git a/dotfiles/.bin/dotfiles b/dotfiles/.bin/dotfiles
--- a/dotfiles/.bin/dotfiles
+++ b/dotfiles/.bin/dotfiles
@@ -20,6 +20,8 @@ function do_module() {
 	do_module_bin "$module_dir" || echo "error" >&2
 	do_module_unconfig "$module_dir" || echo "error" >&2
 	do_module_config "$module_dir" || echo "error" >&2
+	do_module_unintegration_zsh "$module_dir" || echo "error" >&2
+	do_module_integration_zsh "$module_dir" || echo "error" >&2
 	do_module_brewfile "$module_dir" || echo "error" >&2
 }
 
@@ -101,6 +103,32 @@ function do_module_unconfig() (
 	done
 )
 
+function do_module_integration_zsh() (
+	local module_dir="$1"
+	local remote_dir="$(get_integration_zsh_dir)"
+	local local_dir="$module_dir/.integration/zsh"
+
+	[[ ! -e "$local_dir" ]] && return 0
+
+	local f
+	for f in "$local_dir/"*(D); do
+		symlink "$remote_dir/$(basename "$f")" "$f"
+	done
+)
+
+function do_module_unintegration_zsh() (
+	local module_dir="$1"
+	local remote_dir="$(get_integration_zsh_dir)"
+	local local_dir="$module_dir/.integration/zsh"
+
+	[[ ! -e "$remote_dir" ]] && return 0
+
+	local f
+	for f in "$remote_dir/"*(D); do
+		unsymlink "$f" "$module_dir"
+	done
+)
+
 function do_module_brewfile() (
 	local module_dir="$1"
 	local local_file="$module_path/.brewfile"
@@ -120,6 +148,10 @@ function get_bin_dir() {
 
 function get_config_dir() {
 	printf "%s" "$HOME/.config"
+}
+
+function get_integration_zsh_dir() {
+	printf "%s" "$HOME/.local/share/zsh/integration"
 }
 
 function symlink() {
