Add git integration doers

diff --git a/dot/.bin/dot b/dot/.bin/dot
--- a/dot/.bin/dot
+++ b/dot/.bin/dot
@@ -22,6 +22,12 @@ function do_module() {
 	do_module_config "$module_dir" || echo "error" >&2
 	do_module_unintegration_zsh "$module_dir" || echo "error" >&2
 	do_module_integration_zsh "$module_dir" || echo "error" >&2
+	do_module_integration_gitignore "$module_dir" || echo "error" >&2
+	do_module_unintegration_gitignore "$module_dir" || echo "error" >&2
+	do_module_integration_gitconfig "$module_dir" || echo "error" >&2
+	do_module_unintegration_gitconfig "$module_dir" || echo "error" >&2
+	do_module_integration_gitconfigopt "$module_dir" || echo "error" >&2
+	do_module_unintegration_gitconfigopt "$module_dir" || echo "error" >&2
 	do_module_unintegration_tldr "$module_dir" || echo "error" >&2
 	do_module_integration_tldr "$module_dir" || echo "error" >&2
 	do_module_brewfile "$module_dir" || echo "error" >&2
@@ -157,6 +163,100 @@ function do_module_unintegration_tldr() (
 		unsymlink "$f" "$module_dir"
 	done
 )
+
+function do_module_integration_gitignore() (
+	local module_dir="$1"
+	local remote_dir="$(get_integration_gitignore_dir)"
+	local local_dir="$module_dir/.integration/gitignore"
+
+	[[ ! -e "$local_dir" ]] && return 0
+
+	local f
+	for f in "$local_dir/"*(D); do
+		file "$remote_dir/$(basename "$f")" "$f"
+	done
+
+	find "$(get_integration_gitignore_dir)" -mindepth 1 -maxdepth 1 | sort | xargs cat > "$(get_integration_gitignore_file)"
+)
+function do_module_unintegration_gitignore() (
+	local module_dir="$1"
+	local remote_dir="$(get_integration_gitignore_dir)"
+	local local_dir="$module_dir/.integration/gitignore"
+
+	[[ ! -e "$remote_dir" ]] && return 0
+
+	local f
+	for f in "$remote_dir/"*(D); do
+		unsymlink "$f" "$module_dir"
+	done
+)
+function get_integration_gitignore_dir() {
+	printf "%s" "$HOME/.local/share/git/integration-gitignore"
+}
+function get_integration_gitignore_file() {
+	printf "%s" "$HOME/.local/share/git/ignore"
+}
+
+function do_module_integration_gitconfig() (
+	local module_dir="$1"
+	local remote_dir="$(get_integration_gitconfig_dir)"
+	local local_dir="$module_dir/.integration/gitconfig"
+
+	[[ ! -e "$local_dir" ]] && return 0
+
+	local f
+	for f in "$local_dir/"*(D); do
+		file "$remote_dir/$(basename "$f")" "$f"
+	done
+
+	find "$(get_integration_gitconfig_dir)" -mindepth 1 -maxdepth 1 | while IFS= read -r line; do printf '[include]\n\tpath = %s\n' "$line"; done > "$(get_integration_gitconfig_file)"
+)
+function do_module_unintegration_gitconfig() (
+	local module_dir="$1"
+	local remote_dir="$(get_integration_gitconfig_dir)"
+	local local_dir="$module_dir/.integration/gitconfig"
+
+	[[ ! -e "$remote_dir" ]] && return 0
+
+	local f
+	for f in "$remote_dir/"*(D); do
+		unsymlink "$f" "$module_dir"
+	done
+)
+function get_integration_gitconfig_dir() {
+	printf "%s" "$HOME/.local/share/git/integration-gitconfig"
+}
+function get_integration_gitconfig_file() {
+	printf "%s" "$HOME/.local/share/git/config"
+}
+
+function do_module_integration_gitconfigopt() (
+	local module_dir="$1"
+	local remote_dir="$(get_integration_gitconfigopt_dir)"
+	local local_dir="$module_dir/.integration/gitconfigopt"
+
+	[[ ! -e "$local_dir" ]] && return 0
+
+	local f
+	for f in "$local_dir/"*(D); do
+		file "$remote_dir/$(basename "$f")" "$f"
+	done
+)
+function do_module_unintegration_gitconfigopt() (
+	local module_dir="$1"
+	local remote_dir="$(get_integration_gitconfigopt_dir)"
+	local local_dir="$module_dir/.integration/gitconfigopt"
+
+	[[ ! -e "$remote_dir" ]] && return 0
+
+	local f
+	for f in "$remote_dir/"*(D); do
+		unsymlink "$f" "$module_dir"
+	done
+)
+function get_integration_gitconfigopt_dir() {
+	printf "%s" "$HOME/.local/share/git/integration-gitconfigopt"
+}
 
 function do_module_brewfile() (
 	local module_dir="$1"
